### ISSUE TITLE
OdinHorse and FarmCounter

### ISSUE THREAD

**Issue by vapordwarf** [joeyparrish/valheim-farmcounter#5]
Love your mod for boars and lox, but I can't get it to work for horses (from OdinHorse). I have tried any number of permutations of 
${tame_$rae_OdinHorse}
as well as the one you listed in the mod description 
${tame_$odin_horse}
but I cannot get anything other than 0 to show up, even when the horses are practically licking the sign. Any help?

**Comment by vapordwarf** [comment]
So I finally figured it out. Might want to put this info into the mod description, as the description is apparently incorrect regarding OdinHorse horses.
Horses: ${tame_$horse_odin}
Foals: ${all_$horse_offspring}   
Hope this helps someone else.

**Comment by joeyparrish** [comment]
Ah, I put `${tame_$odin_horse}` in the README.  My mistake!  I'll update it.
